[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
workDir = "backend"

[nixpacks]
aptPackages = ["python3", "python3-pip", "python3-dev", "build-essential"]
installCmd = "pip install -r requirements.txt"

[env]
PORT = "8000"
PYTHONPATH = "/app/backend"